sudo: false
language: node_js
node_js:
  - stable
branches:
  only:
    - develop
    - master
cache:
  directories:
    - node_modules
    - test
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
  - npm run coveralls
